"""RendererAgent — deterministic HTML rendering (no LLM calls)."""
import json
import re
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from messaging.agents.base import BaseAgent
from messaging.dto.candidate import Candidate
from messaging.dto.hard_rules import TTS_CHARS_PER_SEC_ZH, TTS_PAUSE_PER_BREAK_SEC, TTS_SLIDE_BUFFER_MS
from messaging.dto.rendered_message import RenderedMessage

TEMPLATES_DIR = Path(__file__).parent.parent.parent / "templates"


def _compute_autoslide(narration: str, slide_types: list[str]) -> dict[str, int]:
    """
    Return {slide_type: autoslide_ms} calibrated to fish.audio playback.
    Formula: speech_time + paragraph_pause_time + slide_transition_buffer
    """
    segments = re.split(r'\[幻灯片: (\w+)\]', narration)
    slide_data: dict[str, tuple[int, int]] = {}  # stype -> (speech_chars, para_breaks)
    for i in range(1, len(segments), 2):
        stype = segments[i]
        content = segments[i + 1].strip() if i + 1 < len(segments) else ""
        speech_chars = len(content.replace("\n", "").replace(" ", ""))
        para_breaks = len(re.findall(r'\n\n+', content))
        slide_data[stype] = (speech_chars, para_breaks)

    result: dict[str, int] = {}
    for stype in slide_types:
        chars, breaks = slide_data.get(stype, (0, 0))
        if chars == 0:
            result[stype] = 30000
            continue
        speech_secs = chars / TTS_CHARS_PER_SEC_ZH
        pause_secs  = breaks * TTS_PAUSE_PER_BREAK_SEC
        total_ms    = int((speech_secs + pause_secs) * 1000) + TTS_SLIDE_BUFFER_MS
        result[stype] = total_ms
    return result


class RendererAgent(BaseAgent):

    def run(self, plan: dict, candidate: Candidate) -> RenderedMessage:
        print("[Renderer] Rendering HTML deck...")

        env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)), autoescape=False)
        template = env.get_template("deck.html.j2")

        md = plan["market_snapshot"]
        price_history = plan["price_history"]["items"]
        price_labels = json.dumps([p["date"] for p in price_history])
        price_values = json.dumps([p["close"] for p in price_history])

        price_change = md.get("price_change_pct", 0) or 0
        price_color = "#22c55e" if price_change >= 0 else "#ef4444"
        price_sign = "+" if price_change >= 0 else ""

        tech = plan["technical_indicators"]
        val = plan["valuation_snapshot"]

        # Overwrite market_overview headline with real numbers (renderer has authority)
        range_pos = md.get("52w_range_position_pct")
        pe_val = val.get("pe_forward") or val.get("pe_trailing")
        change_str = f"{'+' if price_change >= 0 else ''}{price_change}%"
        parts = [f"${md.get('current_price', 'N/A')}  {change_str}"]
        if pe_val:
            parts.append(f"Forward PE {pe_val}x")
        analyst = plan.get("analyst_snapshot", {})
        upside = analyst.get("upside_pct")
        if upside is not None:
            parts.append(f"目标价空间 {'+' if upside >= 0 else ''}{upside}%")
        real_overview_headline = "  ·  ".join(parts)

        slides = candidate.slides
        slide_list = slides.get("slides", [])
        for s in slide_list:
            if s.get("type") == "market_overview":
                s["headline"] = real_overview_headline
                break

        # Compute per-slide autoslide timing from narration character counts
        slide_types = [s["type"] for s in slide_list]
        autoslide_map = _compute_autoslide(candidate.narration, slide_types)
        for s in slide_list:
            s["autoslide_ms"] = autoslide_map.get(s["type"], 30000)

        html = template.render(
            slides=slide_list,
            title=slides.get("title", md["ticker"]),
            ticker=md["ticker"],
            company_name=md.get("company_name", md["ticker"]),
            current_price=md.get("current_price", "N/A"),
            price_change_pct=price_change,
            price_sign=price_sign,
            price_color=price_color,
            market_cap_str=md.get("market_cap_str", "N/A"),
            pe_ratio=val.get("pe_forward") or val.get("pe_trailing") or "N/A",
            high_52w=md.get("52w_high", "N/A"),
            low_52w=md.get("52w_low", "N/A"),
            volume=md.get("volume", "N/A"),
            beta=md.get("beta", "N/A"),
            analyst_target=plan.get("analyst_snapshot", {}).get("target_mean", "N/A"),
            price_labels=price_labels,
            price_values=price_values,
            ma20=tech.get("ma20"),
            ma50=tech.get("ma50"),
        )

        print(f"[Renderer] HTML deck rendered.")
        return html  # caller writes to disk

    def generate_thumbnail(self, plan: dict, youtube_meta: dict) -> str:
        """Render 1280×720 YouTube thumbnail HTML — deterministic, no LLM calls.
        Thumbnail copy is pre-generated by GeneratorAgent inside youtube_meta.
        """
        print("[Renderer] Generating thumbnail...")
        md  = plan["market_snapshot"]
        val = plan["valuation_snapshot"]

        current_date = plan["current_date"]

        # All copy comes from GeneratorAgent — no LLM calls here
        hook      = youtube_meta.get("thumbnail_hook", youtube_meta.get("title", md["ticker"])[:15])
        highlight = youtube_meta.get("thumbnail_highlight", "")
        subhook   = youtube_meta.get("thumbnail_subhook", "")
        verdict   = youtube_meta.get("thumbnail_verdict", "neutral")

        # Build hook_html — wrap highlight in <em>
        if highlight and highlight in hook:
            hook_html = hook.replace(highlight, f"<em>{highlight}</em>", 1)
        else:
            hook_html = hook

        # Font size: shorter hook = bigger font
        hook_font = 76 if len(hook) <= 10 else 64 if len(hook) <= 14 else 54

        # Glow color matches verdict
        glow = {"bullish": (16, 185, 129), "bearish": (244, 63, 94), "neutral": (245, 158, 11)}
        gr, gg, gb = glow.get(verdict, (59, 130, 246))

        accent = {"bullish": "#10b981", "bearish": "#f43f5e", "neutral": "#f59e0b"}.get(verdict, "#3b82f6")

        tech      = plan["technical_indicators"]
        price_change = md.get("price_change_pct", 0) or 0
        fwd_pe   = val.get("pe_forward") or val.get("pe_trailing") or "N/A"
        peg      = val.get("peg")
        rsi      = tech.get("rsi_14")
        inst_pct = md.get("institutional_ownership_pct") or "N/A"

        env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)), autoescape=False)
        tmpl = env.get_template("thumbnail.html.j2")
        html = tmpl.render(
            ticker=md["ticker"],
            company_name=md.get("company_name", md["ticker"]),
            current_date=current_date,
            current_price=md.get("current_price", "N/A"),
            price_change_pct=price_change,
            fwd_pe=fwd_pe,
            peg=round(peg, 2) if peg else None,
            rsi=round(rsi, 1) if rsi else None,
            inst_pct=inst_pct,
            hook_html=hook_html,
            subhook=subhook,
            verdict=verdict,
            hook_font_size=hook_font,
            accent_color=accent,
            glow_r=gr, glow_g=gg, glow_b=gb,
        )
        print(f"[Renderer] Thumbnail: hook='{hook}' | highlight='{highlight}' | verdict={verdict}")
        return html
